apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
        - name: calendar-api
          image: asia-east2-docker.pkg.dev/calendar-web-app-443211/calendar-api/calendar-api:v1.0.7
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "********"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
            - name: DB_NAME
              value: "postgres"
            - name: EMAIL
              value: "********"
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: email-password
                  key: email-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: FRONTEND_URL
              value: "********"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"